// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN27-QcjIVgsgKZPmxkdqMpZKJfvDbITA',
    appId: '1:482458691013:web:85b112029bd555ec5a97ac',
    messagingSenderId: '482458691013',
    projectId: 'flatchore',
    authDomain: 'flatchore.firebaseapp.com',
    storageBucket: 'flatchore.firebasestorage.app',
    measurementId: 'G-L63BG123LQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmoUwnQAPX4RHy0_ygpu_rfAc8-b0W-qg',
    appId: '1:482458691013:ios:2ccff8248abdec9c5a97ac',
    messagingSenderId: '482458691013',
    projectId: 'flatchore',
    storageBucket: 'flatchore.firebasestorage.app',
    iosClientId: '482458691013-h3a23ii2892927eg53k2v34vqg2atimp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flatChore',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmoUwnQAPX4RHy0_ygpu_rfAc8-b0W-qg',
    appId: '1:482458691013:ios:2ccff8248abdec9c5a97ac',
    messagingSenderId: '482458691013',
    projectId: 'flatchore',
    storageBucket: 'flatchore.firebasestorage.app',
    iosClientId: '482458691013-h3a23ii2892927eg53k2v34vqg2atimp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flatChore',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_hDJNhG4dylvhLWJqq5JbjjsQirKcnE',
    appId: '1:482458691013:android:74c65c5e2cc74b345a97ac',
    messagingSenderId: '482458691013',
    projectId: 'flatchore',
    storageBucket: 'flatchore.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN27-QcjIVgsgKZPmxkdqMpZKJfvDbITA',
    appId: '1:482458691013:web:e6fc32ee0c84d7325a97ac',
    messagingSenderId: '482458691013',
    projectId: 'flatchore',
    authDomain: 'flatchore.firebaseapp.com',
    storageBucket: 'flatchore.firebasestorage.app',
    measurementId: 'G-QVHTX9W7Y2',
  );

}